# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n\x07\x43omment\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12(\n\x04sent\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"B\n\x0b\x43ommentMeta\x12\x15\n\rcommentLength\x18\x01 \x01(\x05\x12\x1c\n\x14previousCommentCount\x18\x02 \x01(\x05\x32\x42\n\x0b\x43hatService\x12\x33\n\rRouteComments\x12\r.chat.Comment\x1a\x11.chat.CommentMeta\"\x00\x42\x08Z\x06./ch11b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./ch11'
  _globals['_COMMENT']._serialized_start=53
  _globals['_COMMENT']._serialized_end=136
  _globals['_COMMENTMETA']._serialized_start=138
  _globals['_COMMENTMETA']._serialized_end=204
  _globals['_CHATSERVICE']._serialized_start=206
  _globals['_CHATSERVICE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
